### ISSUE TITLE
etcdctl pipe-pipe OR strangeties

### ISSUE THREAD

**Issue by jspc** [Financial-Times/coco-provisioner#72]
In the cloud-configs there exist lines as per:

```
ExecStart=/bin/sh -c "etcdctl mk /ft/_credentials/wordpress/content_api_key '{{ wordpress_api_key }}' || echo 'Already set' > /dev/null;"
```

I presume the `echo 'Already set' > /dev/null;` is to ensure the command always exits as 0 so errors are ignored so the command doesn't bomb out.

Given the 'Already set' message never makes it anywhere useful, whats the benefit of echoing it out than using `|| true` instead?

**Comment by Zapadlo** [comment]
@jspc None, `|| true` sounds good.

**Comment by Zapadlo** [comment]
Fixed in https://github.com/Financial-Times/coco-provisioner/pull/74
